apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: summit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summit
  template:
    metadata:
      labels:
        app: summit
    spec:
      containers:
      - name: summit-container
        image: marcofenskevi/summits-summit-service
        ports:                               
        - containerPort: 3000                      
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: summit-service
spec:
  selector:
    app: summit
  ports:
  - protocol: TCP
    targetPort: 3000
    port: 80
    name: http
  type: LoadBalancer