apiVersion: v1
kind: Namespace                     
metadata:                 
  name: summits-application
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: summits-ascent-deployment
  namespace: summits-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summits-ascent
  template:
    metadata:
      labels:
        app: summits-ascent
    spec:
      containers:
      - name: summits-container
        image: marcofenskevi/summits-ascent-service:v4
        ports:                               
        - containerPort: 3001                      
          name: http
---
apiVersion: v1  
kind: Service                      
metadata:                 
  name: summits-ascent-service
  namespace: summits-application
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: ascents_mapping
      prefix: /ascents/
      service: summits-ascent-service.summits-application:80
spec:                     
  selector:               
    app: summits-ascent            
  ports:                  
  - protocol: TCP         
    targetPort: 3001      
    port: 80              
    name: http            
  type: LoadBalancer
