apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: summits-ascent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summits-ascent
  template:
    metadata:
      labels:
        app: summits-ascent
    spec:
      containers:
      - name: summits-container
        image: marcofenskevi/summits-ascent-service:v3
        ports:                               
        - containerPort: 3001                      
          name: http
---
apiVersion: v1  
kind: Service                      
metadata:                 
  name: summits-ascent-service     
spec:                     
  selector:               
    app: summits-ascent            
  ports:                  
  - protocol: TCP         
    targetPort: 3001      
    port: 80              
    name: http            
  type: LoadBalancer