apiVersion: v1
kind: Namespace                     
metadata:                 
  name: summits-application
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: summits-general-deployment
  namespace: summits-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: summits-general
  template:
    metadata:
      labels:
        app: summits-general
    spec:
      containers:
      - name: summits-container
        image: marcofenskevi/summits-summit-service:v5
        ports:                               
        - containerPort: 3000                      
          name: http
---
apiVersion: v1
kind: Service                     
metadata:                 
  name: summits-general-service
  namespace: summits-application     
spec:                     
  selector:               
    app: summits-general            
  ports:                  
  - protocol: TCP         
    targetPort: 3000      
    port: 80              
    name: http            
  type: LoadBalancer
